name: Python package

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *' # 매일 UTC 기준 15:00(한국 시간 기준 자정)에 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Set up Environment Variables
      run: |
        echo "APIKEY=${{ secrets.APIKEY }}" >> $GITHUB_ENV
        echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run main.py
      run: |
        python main.py
