name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Acess Secrets
      run: | 
        echo "APIKEY=$APIKEY" >> .env
        echo "TOKEN=$TOKEN" >> .env
      env: 
        APIKEY : ${{secrets.APIKEY}}
        TOKEN : ${{secrets.TOKEN}}
    - name: Run main.py
      run: |
        pip3 install requests
        python3 main.py
